/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _IDL_H_RPCGEN
#define _IDL_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct credentials {
	char login[64];
	char password[64];
};
typedef struct credentials credentials;

struct command {
	char command[256];
	credentials creds;
};
typedef struct command command;

#define COMPUTE 456123789
#define EXECUTE_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define execute 1
extern  char ** execute_1(command *, CLIENT *);
extern  char ** execute_1_svc(command *, struct svc_req *);
#define auth 4
extern  char ** auth_1(credentials *, CLIENT *);
extern  char ** auth_1_svc(credentials *, struct svc_req *);
extern int compute_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define execute 1
extern  char ** execute_1();
extern  char ** execute_1_svc();
#define auth 4
extern  char ** auth_1();
extern  char ** auth_1_svc();
extern int compute_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_credentials (XDR *, credentials*);
extern  bool_t xdr_command (XDR *, command*);

#else /* K&R C */
extern bool_t xdr_credentials ();
extern bool_t xdr_command ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_IDL_H_RPCGEN */
