/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "IDL.h"

/* check credentials of user */
char checkcreds(char login[], char password[])
{
	if(strcmp(login, "qwe") == 0 && strcmp(password, "asd") == 0){
		return 1;
	} else {
		return 0;
	}
}

/* like a string + string in c++ hehehe yes dat is kostil' */
char* add_string(char* first, char second[])
{
	char* full_text;
	full_text= malloc(strlen(first)+strlen(second)+1); 
	strcpy(full_text, first); 
	strcat(full_text, second);
	free(first);
	return full_text;
}

char* cmd_system(const char* command)
{
    char* result = malloc(1);;
	result[0] = 0;
    FILE *fpRead;
    fpRead = popen(command, "r");
    char buf[1024];
    memset(buf,'\0',sizeof(buf));
    while(fgets(buf,1024-1,fpRead)!=NULL)
    {
        result = add_string(result, buf);
    }
    if(fpRead!=NULL)
       pclose(fpRead);
    return result;
}

char **
execute_1_svc(command *argp, struct svc_req *rqstp)
{
	static char * result;
	if(!checkcreds(argp->creds.login, argp->creds.password)){
		result = (char *)"bad credentials";
	} else {
		result = cmd_system(argp->command);
	}
	return &result;
}

char **
auth_1_svc(credentials *argp, struct svc_req *rqstp)
{
	static char * result;

	if(checkcreds(argp->login, argp->password)){
		result = (char *)"ok";
	} else {
		result = (char *)"bad";
	}
	return &result;
}
